### PR TITLE
Force Name Parameter

### PR DESCRIPTION
**Pull request by ethanleifer**
- Change `responseModel<T>.name` to be required
- Add the `response_model.name` parameter to all examples and tests
- Make generic types extend `z.ZodTypeAny` to force schemas to error
- Remove `async` from `chatCompletion` to remove a layer of nested `Promise`'s

Is there anyway to test these cases of typechecking? @roodboi 

response_model.name is undefined: 
Screenshot 2024-01-07 at 7 22 08 PM

If you just have max_retires it also errors (so if you have max_retries you also need response_model but not the other way around)
Screenshot 2024-01-07 at 7 23 03 PM

Type inference still works:
Screenshot 2024-01-07 at 7 24 17 PM

### CODE REVIEW

**Comment by roodboi** [comment]
This looks sick - do the stream results show the right ones too?

**Comment by ethanleifer** [comment]
Worth double checking. All tests pass. 

I think we need to figure out how to make sure we or someone else doesn't break these inferences moving forward

**Comment by roodboi** [comment]
Re: testing types - even though bun will run typescript it won't do any runtime typechecking - so im not sure what good ways to check might be - maybe have a test file that sets something up in a way that depends on the inference, such that if it was wrong the build would fail or something?

**Comment by ethanleifer** [comment]
How is there no way to test types other than with [vitetest](https://vitest.dev/guide/testing-types.html) which doesn't support bun

Feel like this would be super common for maintain a level of dx

**Comment by ethanleifer** [comment]
THIS WORKS!!! https://github.com/loreanvictor/ts-inference-check

**Review by roodboi — APPROVED** [review]

**Pull request merged**
