### PR TITLE
chore(exports): export OAIExtended type

### PR DESCRIPTION
**Pull request by mattzcarey**
I'd like to use `LLMValidator` and `maybe`. Because of the way the project is packaged it needs to be exported to the top level. There are also situations using Instructor where having its type exported is super helpful. 

----

| <a href="https://ellipsis.dev" target="_blank">Ellipsis</a> | :rocket: This PR description was created by [Ellipsis](https://www.ellipsis.dev) for commit 070f1ea305248d5fe80b8c035c64b5d0352b4be2.  | 
|--------|--------|

### Summary:
This PR exports `LLMValidator`, `maybe`, `Maybe`, and `OAIClientExtended` from the top level and corrects a typo in the `maybe` function comment.

**Key points**:
- Added exports for `LLMValidator`, `maybe`, `Maybe`, and `OAIClientExtended` in `/src/index.ts` and `/src/dsl/index.ts`.
- Corrected a typo in the comment of the `maybe` function in `/src/dsl/maybe.ts`.

----
Generated with :heart: by [ellipsis.dev](https://www.ellipsis.dev)

### CODE REVIEW

**Comment by roodboi** [comment]
This looks good - I have been building validators like this custom too - the approach we use here currently works fine as an example and for the tests - but personally I'm not a big fan of requiring an instructor instance to be passed in and having messages hard coded like we have in here.

The big issue though with this is streaming - we run continuous validation during a streamand expose an isValid - which lets you have some understanding of the state of the response before it completes

if you were to use this with stream true it would trigger a shit ton of requests, right?

**Comment by roodboi** [comment]
yeah, 100% - I didn't spend much time in here - so I could be wrong about the stream issue, was just my first thought when looking through it again - I can run it locally and see, but that's my only concern tbh - if people find it valuable then im all about it - as long as we can just make sure folks cant get into a situation where they make like 2000 completion calls because they have stream true lol

**Review by roodboi — DISMISSED** [review]

**Comment by roodboi** [comment]
just confirmed locally it is def creating many many many addt completion calls if stream is present on the origin call

so this is tough - we could hypothetically check for a superRefine or something - and like throw or warn if stream is on - but it might be expected, you might want to make some async check? But I dunno, that's tough.

Or we could extend the responseModel maybe to have like an optional "validators" or something - and you define like a map of them that you could use in ur schema but then we have the ability to force stream false or throw otherwise, maybe?

can try to spend some time thinking about it, but if you have some ideas of what would be a good way to approach plz let me know - also tagging @ethanleifer in who wrote the validator initially

**Comment by mattzcarey** [comment]
> just confirmed locally it is def creating many many many addt completion calls if stream is present on the origin call
> 
> so this is tough - we could hypothetically check for a superRefine or something - and like throw or warn if stream is on - but it might be expected, you might want to make some async check? But I dunno, that's tough.
> 
> Or we could extend the responseModel maybe to have like an optional "validators" or something - and you define like a map of them that you could use in ur schema but then we have the ability to force stream false or throw otherwise, maybe?
> 
> can try to spend some time thinking about it, but if you have some ideas of what would be a good way to approach plz let me know - also tagging @ethanleifer in who wrote the validator initially

I prefer the idea of extending the response model. That is a key part of instructor so having control over that interface makes sense. Disabling validation on streaming by default does make sense. Could add some function to validate every n tokens continuously also.

**Comment by ethanleifer** [comment]
I am slightly leaning more towards keeping the validators on zod schema because that is how zod and instructor-py both do it. The response_model object is really just a way to pass the zod schema through to the instructor. 

Maybe we make it instructor.LLMValidator so you don't have to pass through instructor separately?

I think either validating on every n chunks or only trigger the refine on finished model

**Review by roodboi — APPROVED** [review]

**Pull request merged**
