### PR TITLE
fix: use CJS shims for stream

### PR DESCRIPTION
**Pull request by morgante**
Explicitly importing the `.mjs` module breaks CommonJS compatibility, we should instead import the `streaming` path which will choose between ESM and CommonJS automatically.

### CODE REVIEW

**Comment by morgante** [comment]
@roodboi Can you take a look?

**Review by roodboi — APPROVED** [review]
looks good, thanks!

**Comment by jeremypress** [comment]
whoops, opened here as well https://github.com/instructor-ai/instructor-js/pull/180. closing mine

**Comment by jeremypress** [comment]
hey @morgante 👋🏻  @roodboi can land? I'd like to remove my pnpm patch so I can distribute my code

**Comment by morgante** [comment]
Yes I think @roodboi needs to merge.

**Comment by pakamienny** [comment]
hey has this been solved?
I am still running into an error:

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/pakamienny/Documents/hackathons/batman/node_modules/openai/streaming.mjs not supported.
Instead change the require of /Users/pakamienny/Documents/hackathons/batman/node_modules/openai/streaming.mjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/pakamienny/Documents/hackathons/batman/node_modules/@instructor-ai/instructor/dist/index.cjs:1:806) {
  code: 'ERR_REQUIRE_ESM'
}

**Pull request merged**
